### ISSUE TITLE
authenticated user "user1" cannot access acl-test/basic-authenticated route

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#10]
> development.ERROR: No permission set for the requested route, path [acl-test/basic-authenticated], method [GET] and action name [App\Http\Controllers\TestController@acl_test_basic_authenticated], guest [], username [user1].

This is after I've merged upstream/master, `composer dump-autoload` and `php artisan migrate:refresh --seed`  (both ProductionSeeder & DevelopmentSeeder have been seeded).

This is strange as, by default, I see that "user1" has role "Users", and the "Users" role in turn has the "Basic Authenticated" permission.
i.e. When viewing "user1" at `/admin/users/2` and going to the "Permissions" tab, I see that "Basic Authenticated" has a check-mark under the "Effective" column but not under the "Assigned" column (which is expected as the permission is not directly assigned to the user but rather to the role that's assigned to the user).

What gives?

**Comment by tamer-hassan** [comment]
I guess the error was self-explanatory.. There was indeed no valid permission associated with the aforementioned route, and all the other testing routes. I was expecting this was established by default, but I was wrong.

My question now is: Did you also unintentionally miss setting permission_id to 8 for  `admin/audit/{userId}/show` as with `admin/audit` ?
![Missing route permissions](http://i64.tinypic.com/25gasgl.png)

**Comment by sroutier** [comment]
Hello, 
I just double checked and you are correct on both counts. The routes under "acl-test/*" and the route "admin/audit/{userId}/show" do not have permissions assigned to them. That was an oversight sorry about the trouble.
I also noted that the parameter in the audit route definition should be "auditId" instead of "userId", a little too much cut-&-paste if you ask me... 

I am currently working on the crumb-trail and dynamic menu based on permissions, and I will make sure to fix this in the next patch.

Thanks for creating the issue.
/s

**Comment by tamer-hassan** [comment]
Dear Sebastian,

I'm eager to see your next patch, at least including the crumb-trail and dynamic menu based on permissions, so I don't have to reinvent the wheel. :-)

**Comment by sroutier** [comment]
Fixed in commit 30d696faa3d55f254369de37e49a0cf6f7f517df.
