### ISSUE TITLE
How to point to non-minified css?

### ISSUE THREAD

**Issue by sam452** [leskhq/Laravel-Enterprise-Starter-Kit#36]
Thanks for sharing this project. It helps me to learn Laravel. While my app's .env file is set to Development, I'm finding that the gulp.js file is not pointing to the themes, so it's ignoring these files when they change. 

I believe I can run gulp --production to update the min files, but for development, I'd rather continue using the non-minified css files? As a Laravel beginner, what am I overlooking to have Laravel use the non-production css files?

**Comment by sroutier** [comment]
Hello Sam,

Sorry for taking so long to answer your question. Are you trying to access the project's own non-minified CSS files such as the `all.css` compiled from `app.css`, which itself comes from `app.scss` or are your trying to access the CSS file from the dependencies such as Bootstrap or AdminLTE?

I kept CSS from the dependencies separate and intact in order to make maintenance and upgrading easier, but this has the effect of forcing the minified versions on all of us and for all environments. In reality you should not have to modify those, and in fact you should really think twice before tweaking them, so forcing the minified versions did not appear to be a big problem. What I have done at times in order to be able to read them is temporarily and manually change the reference in the master layout from the minified version to the un-minified version, just have to remember to revert the change before committing any changes otherwise you risk having the non-minified version used in PROD.

As for the project's own CSS files they get compiled when you call `gulp` and in DEV if you call it without the `--production` parameter they do not get minified.

Does that answer your question?

Cheers.
/S
