### ISSUE TITLE
Seeding Problem

### ISSUE THREAD

**Issue by sammy-kariuki** [leskhq/Laravel-Enterprise-Starter-Kit#44]
Hello, 
I have been able to set up the project but I cannot seed. When I run the 'php artisan db:seed', I get the following error.

  [Tylercd100\LERN\Exceptions\NotifierFailedException]  
  Expected response code 220 but got code "", with message ""  

  [Swift_TransportException]  
  Expected response code 220 but got code "", with message ""

Any help on this?

Best Regards, 

Sammy.

**Comment by sroutier** [comment]
Hey @SammyHash,

Thanks for logging the issue. Found a couple of problems actually.
Please refresh your copy of the project and try again, let me know if you have any other problems.

FYI: The error that you are seeing is probably because your mail system is not properly configured, this combined with a couple coding mistakes and you are left with an error that make no sense.
I made a newbie mistake and had the password change code in the model fire off an notification email instead of putting that code in the controller. That is why when the seed command is invoked it tries to send an email notification. 
Because of your issue, I changed a few things around
1) Move the email notification code in the controller, that will prevent the seed command from crashing if the mail system is not configured.
2) Added a new configuration setting to enable/disable email notifications. With a default to false, it allows the administrator to build and use the system before having the entire mail system configured.

Thanks again.
/S

**Comment by sammy-kariuki** [comment]
I have been able to seed even without configuring the email system first. 
Thank you very much for the quick response.

**Comment by sroutier** [comment]
You are Welcome.
Enjoy.
