### ISSUE TITLE
menu system - creating a menu-item with a route that requires ID (e.g. movies/44/edit)

### ISSUE THREAD

**Issue by VickG** [leskhq/Laravel-Enterprise-Starter-Kit#46]
In my case, I want to have a menu node that is using a route that takes an ID. 

e.g. 
movies/44/edit

Is there currently a way to manage this? Depending on the logged in user, the ID will be different. Or else I would have used the "URL" field of the menu item.

**Comment by sroutier** [comment]
Hello VickG,

I am not entirely sure what you mean by "menu node that is using a route
that takes an ID" and "Depending on the user the ID will be different".

What would this menu look like? Can you give me a use case to help picture
it?

Would you have a parent menu node called "Users Favorite Movies" and under
list a few menu entries to a movie?
Some things like this:

| Menu | Route |
| --- | --- |
| Users Favorite Movies | users/{userID}/fav_movies |
| \  Star Trek | users/{userID}/fav_movies/{movieID} |
| \+  Star Wars | users/{userID}/fav_movies/{movieID} |

Is a menu like that what you have in mind?
Do you have an idea about how would you build such a variable menu in the
first place?

/s

**Comment by VickG** [comment]
Yes that is exactly what I have in mind as you mentioned. 

How do I create a menu-element using your menu system that uses a route like:
users/{userID}/fav_movies

I picked the correct route from the Routes dropdown and I put this in the "URL" field
users/{id}/fav_movies
but no luck..

Any advice?

**Comment by VickG** [comment]
I will take it that this is not currently supported?

**Comment by sroutier** [comment]
Sorry, busy week-end and I did not get a chance to reply to your question.
The issue is that when the URL is resolved to create the HTML menu entry, all variables ({userID} in your case) must be known to the rendering function in the MenuHandler. 

I think that you have 2 options:
1. Build a menu to your own controller with the URL/Route "users/fav_movies" that will resolve all required variables and either:
   A. Directly render the favorite movies view for the desired user or
   B. Redirect to the route that you want (i.e. "users/{userID}/fav_movies").
2. Create your own MenuHandler that knows what variables will be needed, resolves them and replace them in the route URL before rendering the menu entry. Look at the "generateUrl()" function of the MenuHandler that you are currently using for example the "L51ESKSecuredMenuHandler" first tries to get the URL from the route if configured if that fails it gets it from the URL, right before the function returns if where I would replace any variable in the URL with resolved values. 

Hope that helps a little. Let me know what you think.
/s

**Comment by VickG** [comment]
ok, thank you.. I will close this.
