### ISSUE TITLE
Menu routes not correct when app is in a path other than root

### ISSUE THREAD

**Issue by salhdev** [leskhq/Laravel-Enterprise-Starter-Kit#55]
Hi,

I have installed a test app under http://localhost/l51esk and all the menu paths are being generated as if the app was running in http://localhost/ !

The solution I found, and I am not sure it's the best place to correct this issue, I'll let Sebastian confirm this : 
in the file L51ESKSecuredMenuHandler.php function generateUrl(Menu $menu)
replace : return $url;
by  return \Request::getBasePath() . $url;

This does the trick of course, all the hard coded paths in the blade templates should be corrected as well like in auth/login.blade.php 
the lines :  <form class="form-signin" method="POST" action="/l51/auth/login" >
should be replaced by :  <form class="form-signin" method="POST" action="{!! route('login') !!}" >
Thanks,
Salh

**Comment by sroutier** [comment]
Hello @sraffali,

The example code that you wanted to display to show how to fix the hard coded paths did not make it in the issues, can you confirm that this is what you meant?
Change hard coded URL from this

```
        <form class="form-signin" method="POST" action="/auth/login" >
```

to this:

```
        <form class="form-signin" method="POST" action="auth/login" >
```

Otherwise your fix in the Menu handler looks good. I just have to setup an instance under a path to test it properly and fix all paths...

Thanks again.
/s

**Comment by salhdev** [comment]
Hi sorry, hère it is : action="{!! route('login') !!}" 

Yes the modification i had made did resolve the issue.
My question to you was do you think that's a good place for it or there is a better place for it ?

**Comment by sroutier** [comment]
Hello,

You found the correct place where to fix the issue, but I am wondering if instead of using `\Request::getBasePath()` to build the final URL we should not be using `Config("app.url");`. I have to run a few test to be sure.

I have having some problems running LESK under a subpath. Are you using Apache? Did you modify the `.htaccess` file under the `public/` folder? Would you mind sharing your Apache config?

I have a HTTPD config file `/etc/httpd/conf.d/lesk-sp.conf` containing:

```
Alias /lesk-sp /var/www/lesk-sp/public

<Directory "/var/www/lesk-sp/public">
  AllowOverride all
  Order allow,deny
  Allow from all
</Directory>
```

And the default unmodified `.htaccess` file.
When I try to open the URL `http://vmweb01.vmdom/lesk-sp/`, it first successfully gets redirected to `http://vmweb01.vmdom/lesk-sp/welcome` but then fails with the error:

```
Not Found

The requested URL /var/www/lesk-sp/public/index.php was not found on this server.
```

So the PHP application partially works but then something fails.... I have to run but I will try to check this later tonight.

Cheers.
/S

**Comment by salhdev** [comment]
Hello
You need to add 
RewriteBase /lesk-sp/

This should resolve it .
Let me know.

Regards,
Salh

**Comment by salhdev** [comment]
Hi Sebastien,
It seems that my post last night was hanging on my tablet and did not go through !
Here is my full .htaccess

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>
    RewriteEngine On
    RewriteBase /lesk-sp/
    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]
    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

```

As for the config I personally like it better when the system can figure it out on its own without having to configure it manually. As more and more functionality gets added, it becomes quite complicated to get all the config options in place correctly in order to have a working system.
So if you ask me, I'd leave it to `\Request::getBasePath()` since it will work for both cases (root or subdir).

Cheers,
S.

**Comment by sroutier** [comment]
Hello @sraffali,

Thanks for the tip on the `.htaccess` file. That is all that I was missing. I added a note in the README to help others just in case.

You are right about the use of `\Request::getBasePath()` vs. `Config("app.url");`. I just wanted to make sure that the config option was not useful in scenario with Fail-Over and Load-Balancing, but it looks like the config option is only used for some artisan commands that do not have access to a Request object.

I fixed all the hard coded URLs in the action, href and src. Should all work now.
Thanks for the help.

/s
