### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by bukowskiadam** [leskhq/Laravel-Enterprise-Starter-Kit#80]
At first I'd like to say hello :wink: 

I've got a question about licensing.

According to [Drupal's license FAQ](https://www.drupal.org/about/licensing#q7), each module/extension written to the GPL software should be also GPL licensed. Your [lesk-modules](https://github.com/sroutier/lesk-modules) is not.

Why you've changed the license from the MIT to GPL for *lesk*?

Best regards,
Adam

**Comment by sroutier** [comment]
Hello Adam,

Thank for the note and question.
You are right I forgot to include the license on some of the modules and to update it for the LESK-Module. I will rectify this ASAP.

Now on to the bigger question: Why GPLv3 over the MIT license?
The MIT license is simple and short, and it grants a lot of freedom but perhaps a little too much. I prefer the GPLv3 license as it has provisions protecting against DRM and Patents. 

Does that answer your question? Let me know if you have any other questions or issues.
Thanks.
/S

**Comment by bukowskiadam** [comment]
Yes it answers, however I'm still in doubt about creating application around LESK, because if I properly understand GPL license each module/extension has to be GPL also. So for instance I'll create some data import module that I'd like to sell (giving the source code - not SaaS), it has to be GPL, so buyer can redistribute it for free. Have you considered LGPL license? I believe it allows to create paid extension on custom license.

Best regards,
Adam

**Comment by sroutier** [comment]
Hello Adam,

Sorry about the delay, I am not ignoring you, I am just unsure what to answer just yet. I need to do a little more research and thinking about this.

Here is your request as I see it:
You are trying to protect your intellectual property and prevent someone else reselling your work without authorization and cutting you out of the deal.
As a person that must put food on the table, I understand the struggle.

The issue is that I cannot find a license that reconciles the requirements:
1) Protect the revenue stream of the developer by preventing unauthorized resell by the client.
2) Protect the freedom of the client by forcing the developer to deliver the source code while granting permission to modify and distribute it.

These two requirements seem, to me, mutually exclusive; also preventing redistribution and resell, with or without modification, would be counter to the ideals of Open Source.

As your pointed out, the LGPL does allow linking proprietary & closed-source code with LGPL libraries, but according to my reading and interpretation, these are self-contained LGPL libraries that are used by proprietary applications and where the closed source application is not a derivative of the library but instead simply uses the library. In the case of LESK and LESK-Modules things are a little different, here LESK-Modules (the library in legal speak) is a derivative of LESK and therefore would have to be licensed under GPL as well.

In my experience, protecting the product (source code in this case) from theft and loss of revenue, is time consuming and counterproductive. If you are dealing with crooks, they will steal it no matter what you do. If they are crafty, they can even get around a license. A better approach would be to develop a positive relationship and foster an environment where collaboration and contributions are not only encouraged but seen as beneficial for all parties. I realise this is not always easy.

I would really like to know what you think about all this, and continue this conversation.

Thank you.
/S

**Comment by bukowskiadam** [comment]
You don't have to apologize me for the delay - I know that's not so important thing and I don't await for the response so quickly :wink: I'm glad that you're open to discussion.

It was really hard to me to keep some logic in my response, so treat all below as a loose bunch of thoughts. Also there is no certain purpose in this post. Please don't feel, that I'm trying to convince you to relicense LESK or something else. I've asked my original question just to know your opinion. You can close this issue anytime you wish.

---

I'm not sure about your interpretation of LGPL and LESK modules.
Imagine we've got core GPL laravel app and the module A for this app.
In my opinion core app have to be considered as a library for the module A, because A won't work without core app.
But it's my interpretation.

---

According to the licensing and protecting developer/customer,
I'd like to be the software license like you've got rights for the things you buy (e.g. phone)

1. You can modify it - you're warranty is void, but you can do this,
2. you can sell it - you loose your rights for it, 
3. you can use just one copy of it.

In software world there is a problem that you can clone it with no cost.

---

I agree that protecting the source code is counterproductive, but giving ability
to legally share your hard work for free is not a good deal.

Basing on GPL library forces me to use GPL - where is my freedom? :wink:

But seriously it's up to each developer to choose the license. I was just curious about your opinion on this case.

I totally agree with mongodb licensing. Database engine is AGPL, but each driver is Apache licensed, so your software does not have to be GPL compatible, but AGPL core forces developers to share their changes.


Best regards,
Adam

**Comment by sroutier** [comment]
Hello Adam, I know it took for ever, and I apologise for this, but after serious consideration and discussion with other members of the open-source community and an intellectual property lawyer, I have come to see things as you suggested it.
The LESK core and a few modules, developed along are licensed GPLv3.
The LESK-Modules package is licensed Apache-2.

As you pointed out this provides the best balance between protecting users by guaranteeing that the core remains Open-source, while not forcing modules developer to release the code if they choose not to.

Thank you for pointing these out to me, and again sorry for the delay.
/s
